-- Phase 2b batch 1: translations for 30 existing master_ingredients rows (a–c)
-- Hand-translated, continental French / Castilian Spanish / Hochdeutsch / Brazilian Portuguese.

UPDATE master_ingredients SET name_fr = 'purée d''açaï',              name_es = 'pulpa de açaí',                    name_de = 'Açaí-Püree',                        name_pt = 'polpa de açaí'                          WHERE name = 'acai puree';
UPDATE master_ingredients SET name_fr = 'sirop de cerises amarena',   name_es = 'sirope de cerezas amarena',        name_de = 'Amarenakirschen-Sirup',             name_pt = 'calda de cerejas amarena'                WHERE name = 'amarena cherry syrup';
UPDATE master_ingredients SET name_fr = 'liqueur d''amaretto',        name_es = 'licor de amaretto',                name_de = 'Amaretto-Likör',                    name_pt = 'licor de amaretto'                       WHERE name = 'amaretto liqueur';
UPDATE master_ingredients SET name_fr = 'extrait d''anis',            name_es = 'extracto de anís',                 name_de = 'Anisextrakt',                       name_pt = 'extrato de anis'                         WHERE name = 'anise extract';
UPDATE master_ingredients SET name_fr = 'abricots',                   name_es = 'albaricoques',                     name_de = 'Aprikosen',                         name_pt = 'damascos'                                WHERE name = 'apricots';
UPDATE master_ingredients SET name_fr = 'purée de banane',            name_es = 'puré de plátano',                  name_de = 'Bananenpüree',                      name_pt = 'purê de banana'                          WHERE name = 'banana puree';
UPDATE master_ingredients SET name_fr = 'mûres',                      name_es = 'moras',                            name_de = 'Brombeeren',                        name_pt = 'amoras silvestres'                       WHERE name = 'blackberries';
UPDATE master_ingredients SET name_fr = 'purée de mûres',             name_es = 'puré de moras',                    name_de = 'Brombeerpüree',                     name_pt = 'purê de amora'                           WHERE name = 'blackberry puree';
UPDATE master_ingredients SET name_fr = 'purée de cassis',            name_es = 'puré de grosella negra',           name_de = 'Schwarze-Johannisbeer-Püree',       name_pt = 'purê de cassis'                          WHERE name = 'blackcurrant puree';
UPDATE master_ingredients SET name_fr = 'myrtilles',                  name_es = 'arándanos',                        name_de = 'Heidelbeeren',                      name_pt = 'mirtilos'                                WHERE name = 'blueberries';
UPDATE master_ingredients SET name_fr = 'purée de myrtilles',         name_es = 'puré de arándanos',                name_de = 'Heidelbeerpüree',                   name_pt = 'purê de mirtilo'                         WHERE name = 'blueberry puree';
UPDATE master_ingredients SET name_fr = 'mélange myrtille-citron',    name_es = 'mezcla de arándano y limón',       name_de = 'Heidelbeer-Zitronen-Mischung',      name_pt = 'mistura de mirtilo e limão'              WHERE name = 'blueberry-lemon blend';
UPDATE master_ingredients SET name_fr = 'sauce butterscotch',         name_es = 'salsa de butterscotch',            name_de = 'Butterscotch-Sauce',                name_pt = 'calda de butterscotch'                   WHERE name = 'butterscotch sauce';
UPDATE master_ingredients SET name_fr = 'arôme gâteau d''anniversaire', name_es = 'extracto de masa de pastel',      name_de = 'Kuchenteig-Aroma',                  name_pt = 'extrato de massa de bolo'                WHERE name = 'cake batter extract';
UPDATE master_ingredients SET name_fr = 'Campari',                    name_es = 'Campari',                          name_de = 'Campari',                           name_pt = 'Campari'                                 WHERE name = 'Campari';
UPDATE master_ingredients SET name_fr = 'melon cantaloup',            name_es = 'melón cantalupo',                  name_de = 'Cantaloupe-Melone',                 name_pt = 'melão cantalupo'                         WHERE name = 'cantaloupe';
UPDATE master_ingredients SET name_fr = 'lait de céréales',           name_es = 'leche de cereales',                name_de = 'Cereal-Milch',                      name_pt = 'leite de cereal'                         WHERE name = 'cereal milk';
UPDATE master_ingredients SET name_fr = 'champagne',                  name_es = 'champán',                          name_de = 'Champagner',                        name_pt = 'champanhe'                               WHERE name = 'champagne';
UPDATE master_ingredients SET name_fr = 'cerises',                    name_es = 'cerezas',                          name_de = 'Kirschen',                          name_pt = 'cerejas'                                 WHERE name = 'cherries';
UPDATE master_ingredients SET name_fr = 'jus de cerise',              name_es = 'jugo de cereza',                   name_de = 'Kirschsaft',                        name_pt = 'suco de cereja'                          WHERE name = 'cherry juice';
UPDATE master_ingredients SET name_fr = 'purée de cerises',           name_es = 'puré de cereza',                   name_de = 'Kirschpüree',                       name_pt = 'purê de cereja'                          WHERE name = 'cherry puree';
UPDATE master_ingredients SET name_fr = 'morceaux de chocolat',       name_es = 'trozos de chocolate',              name_de = 'Schokoladenstücke',                 name_pt = 'pedaços de chocolate'                    WHERE name = 'chocolate chunks';
UPDATE master_ingredients SET name_fr = 'préparation pudding chocolat instantané', name_es = 'mezcla instantánea de pudín de chocolate', name_de = 'Schoko-Instant-Pudding-Pulver', name_pt = 'mistura de pudim de chocolate instantâneo' WHERE name = 'chocolate instant pudding mix';
UPDATE master_ingredients SET name_fr = 'jus de clémentine',          name_es = 'jugo de clementina',               name_de = 'Clementinensaft',                   name_pt = 'suco de clementina'                      WHERE name = 'clementine juice';
UPDATE master_ingredients SET name_fr = 'lait de coco',               name_es = 'leche de coco',                    name_de = 'Kokosmilch',                        name_pt = 'leite de coco'                           WHERE name = 'coconut milk';
UPDATE master_ingredients SET name_fr = 'jus de canneberge',          name_es = 'jugo de arándano rojo',            name_de = 'Cranberrysaft',                     name_pt = 'suco de cranberry'                       WHERE name = 'cranberry juice';
UPDATE master_ingredients SET name_fr = 'sauce à la canneberge',      name_es = 'salsa de arándano rojo',           name_de = 'Cranberrysauce',                    name_pt = 'molho de cranberry'                      WHERE name = 'cranberry sauce';
UPDATE master_ingredients SET name_fr = 'biscuits écrasés',           name_es = 'galletas trituradas',              name_de = 'zerdrückte Kekse',                  name_pt = 'biscoitos esmagados'                     WHERE name = 'crushed cookies';
UPDATE master_ingredients SET name_fr = 'biscuits Oreo écrasés',      name_es = 'galletas Oreo trituradas',         name_de = 'zerdrückte Oreo-Kekse',             name_pt = 'biscoitos Oreo esmagados'                WHERE name = 'crushed Oreo cookies';
UPDATE master_ingredients SET name_fr = 'lavande séchée',             name_es = 'lavanda seca',                     name_de = 'getrockneter Lavendel',             name_pt = 'lavanda seca'                            WHERE name = 'dried lavender';
