-- Phase 2c batch 3: remaining ~60 new master_ingredients rows (M-Z) + remaining links

-- "malted milk powder (Ovaltine or Horlicks)" links to existing 'malted milk powder' master row
INSERT INTO master_ingredients (name, slug, category, aliases, name_fr, name_es, name_de, name_pt) VALUES
  ('maraschino cherries, chopped', 'maraschino-cherries-chopped', 'fruit', '{}',
    'cerises au marasquin hachées', 'cerezas al marrasquino picadas',
    'gehackte Maraschino-Kirschen', 'cerejas maraschino picadas'),
  ('medjool dates, pitted and chopped', 'medjool-dates-pitted-chopped', 'fruit', '{}',
    'dattes medjool dénoyautées et hachées', 'dátiles medjool sin hueso y picados',
    'entsteinte und gehackte Medjool-Datteln', 'tâmaras medjool sem caroço e picadas'),
  ('mini chocolate-almond butter cups, chopped', 'mini-chocolate-almond-butter-cups-chopped', 'chocolate', '{}',
    'mini coupelles chocolat-beurre d''amande hachées', 'mini copitas de chocolate y mantequilla de almendra picadas',
    'gehackte Mini-Schoko-Mandelbutter-Cups', 'mini copinhos de chocolate e pasta de amêndoa picados'),
  ('Mint Oreo cookies, crushed', 'mint-oreo-cookies-crushed', 'other', '{}',
    'biscuits Oreo à la menthe écrasés', 'galletas Oreo de menta trituradas',
    'zerdrückte Minz-Oreo-Kekse', 'biscoitos Oreo de menta esmagados'),
  ('mixed berry compote', 'mixed-berry-compote', 'fruit', '{}',
    'compote de fruits rouges', 'compota de bayas mixtas',
    'gemischtes Beerenkompott', 'compota de frutas vermelhas mistas'),
  ('mixed berry jam (strawberry, blueberry, raspberry)', 'mixed-berry-jam-new', 'condiment', '{}',
    'confiture de fruits rouges (fraise, myrtille, framboise)', 'mermelada de bayas mixtas (fresa, arándano, frambuesa)',
    'gemischte Beerenmarmelade (Erdbeere, Heidelbeere, Himbeere)', 'geleia de frutas vermelhas (morango, mirtilo, framboesa)'),
  ('natural peanut butter', 'natural-peanut-butter', 'other', '{}',
    'beurre de cacahuète naturel', 'mantequilla de maní natural',
    'natürliche Erdnussbutter', 'pasta de amendoim natural'),
  ('oat streusel crumbles', 'oat-streusel-crumbles', 'grain', '{}',
    'miettes de streusel à l''avoine', 'migas de streusel de avena',
    'Hafer-Streuselbrösel', 'farelinhos de streusel de aveia'),
  ('oat cobbler crumbles', 'oat-cobbler-crumbles', 'grain', '{"oat cobbler crumbles (baked + cooled)"}',
    'miettes de cobbler à l''avoine', 'migas de cobbler de avena',
    'Hafer-Cobbler-Brösel', 'farelinhos de cobbler de aveia'),
  ('oat-almond streusel crumbles', 'oat-almond-streusel-crumbles', 'grain', '{}',
    'miettes de streusel avoine-amandes', 'migas de streusel de avena y almendra',
    'Hafer-Mandel-Streuselbrösel', 'farelinhos de streusel de aveia e amêndoa'),
  ('pancake crumbles (or graham crackers)', 'pancake-crumbles', 'grain', '{}',
    'miettes de crêpes (ou biscuits graham)', 'migas de panqueques (o galletas graham)',
    'Pfannkuchen-Brösel (oder Graham-Cracker)', 'farelinhos de panqueca (ou biscoitos graham)'),
  ('pie crust crumbles', 'pie-crust-crumbles', 'grain', '{}',
    'miettes de pâte à tarte', 'migas de masa de tarta',
    'Mürbeteig-Brösel', 'farelinhos de massa de torta'),
  ('pineapple puree', 'pineapple-puree', 'fruit', '{}',
    'purée d''ananas', 'puré de piña', 'Ananaspüree', 'purê de abacaxi'),
  ('pink peppercorns, lightly crushed', 'pink-peppercorns-lightly-crushed', 'spice', '{}',
    'poivre rose légèrement écrasé', 'granos de pimienta rosa ligeramente triturados',
    'rosa Pfefferkörner, leicht zerdrückt', 'grãos de pimenta rosa levemente amassados'),
  ('powdered sugar for dusting', 'powdered-sugar-dusting', 'sugar', '{}',
    'sucre glace pour saupoudrer', 'azúcar glas para espolvorear',
    'Puderzucker zum Bestäuben', 'açúcar de confeiteiro para polvilhar'),
  ('raisin bread crumbles, toasted', 'raisin-bread-crumbles-toasted', 'grain', '{}',
    'miettes de pain aux raisins grillées', 'migas de pan con pasas tostadas',
    'geröstete Rosinenbrot-Brösel', 'farelinhos de pão com passas torrados'),
  ('raisins', 'raisins-plain', 'fruit', '{}',
    'raisins secs', 'pasas', 'Rosinen', 'passas'),
  ('raspberry sauce', 'raspberry-sauce', 'condiment', '{}',
    'sauce à la framboise', 'salsa de frambuesa', 'Himbeersauce', 'calda de framboesa'),
  ('ripe avocado, mashed smooth', 'ripe-avocado-mashed', 'fruit', '{}',
    'avocat mûr écrasé en purée lisse', 'aguacate maduro machacado hasta quedar suave',
    'reife Avocado, glatt zerdrückt', 'abacate maduro amassado até ficar liso'),
  ('roasted macadamia nuts, chopped', 'roasted-macadamia-nuts-chopped', 'nut', '{}',
    'noix de macadamia grillées hachées', 'nueces de macadamia tostadas picadas',
    'gehackte geröstete Macadamianüsse', 'nozes-macadâmia torradas e picadas'),
  ('roasted salted cashews, chopped', 'roasted-salted-cashews-chopped', 'nut', '{}',
    'noix de cajou salées et grillées hachées', 'anacardos tostados con sal picados',
    'gehackte geröstete gesalzene Cashews', 'castanhas de caju torradas e salgadas picadas'),
  ('saffron threads', 'saffron-threads', 'spice', '{}',
    'pistils de safran', 'hebras de azafrán', 'Safranfäden', 'pistilos de açafrão'),
  ('salted roasted peanuts, chopped', 'salted-roasted-peanuts-chopped', 'nut', '{}',
    'cacahuètes grillées salées hachées', 'cacahuetes tostados y salados picados',
    'gehackte geröstete gesalzene Erdnüsse', 'amendoins torrados e salgados picados'),
  ('semi-sweet chocolate chips', 'semi-sweet-chocolate-chips', 'chocolate', '{}',
    'pépites de chocolat mi-amer', 'chispas de chocolate semidulce',
    'halbsüße Schokoladenstückchen', 'gotas de chocolate meio amargo'),
  ('shortbread cookie crumbles', 'shortbread-cookie-crumbles', 'grain', '{}',
    'miettes de sablés', 'migas de galleta de mantequilla',
    'Mürbeteigkeks-Brösel', 'farelinhos de biscoito amanteigado'),
  ('shredded coconut, toasted', 'shredded-coconut-toasted', 'fruit', '{}',
    'noix de coco râpée grillée', 'coco rallado tostado',
    'geröstete Kokosraspeln', 'coco ralado torrado'),
  ('smoked sea salt', 'smoked-sea-salt', 'seasoning', '{}',
    'sel de mer fumé', 'sal marina ahumada', 'geräuchertes Meersalz', 'sal marinho defumado'),
  ('snickerdoodle cookies, crumbled', 'snickerdoodle-cookies-crumbled', 'other', '{}',
    'biscuits snickerdoodle émiettés', 'galletas snickerdoodle desmenuzadas',
    'zerbröselte Snickerdoodle-Kekse', 'biscoitos snickerdoodle esfarelados'),
  ('Snickers bars, chopped', 'snickers-bars-chopped', 'other', '{}',
    'barres Snickers hachées', 'barras Snickers picadas',
    'gehackte Snickers-Riegel', 'barras Snickers picadas'),
  ('soft goat cheese (chevre)', 'soft-goat-cheese-chevre', 'cheese', '{}',
    'fromage de chèvre frais', 'queso de cabra fresco',
    'weicher Ziegenkäse (Chèvre)', 'queijo de cabra fresco'),
  ('soft nougat candy, chopped', 'soft-nougat-candy-chopped', 'other', '{}',
    'nougat mou haché', 'turrón blando picado', 'weicher Nougat gehackt', 'nougat macio picado'),
  ('stewed rhubarb compote', 'stewed-rhubarb-compote', 'fruit', '{}',
    'compote de rhubarbe', 'compota de ruibarbo', 'gedünstetes Rhabarberkompott', 'compota de ruibarbo'),
  ('sugar-free hot fudge sauce', 'sugar-free-hot-fudge-sauce', 'chocolate', '{}',
    'sauce fudge chaude sans sucre', 'salsa de fudge caliente sin azúcar',
    'zuckerfreie heiße Fudge-Sauce', 'calda de fudge quente sem açúcar'),
  ('sugar-free Oreo cookies, crushed', 'sugar-free-oreo-cookies-crushed', 'other', '{}',
    'biscuits Oreo sans sucre écrasés', 'galletas Oreo sin azúcar trituradas',
    'zuckerfreie zerdrückte Oreo-Kekse', 'biscoitos Oreo sem açúcar esmagados'),
  ('sugar-free sprinkles', 'sugar-free-sprinkles', 'sugar', '{}',
    'vermicelles sans sucre', 'grajeas sin azúcar', 'zuckerfreie Streusel', 'granulado sem açúcar'),
  ('sweetened shredded coconut', 'sweetened-shredded-coconut', 'fruit', '{}',
    'noix de coco râpée sucrée', 'coco rallado endulzado',
    'gezuckerte Kokosraspeln', 'coco ralado adoçado'),
  ('sweetener of choice', 'sweetener-of-choice', 'sweetener', '{}',
    'édulcorant au choix', 'edulcorante al gusto',
    'Süßungsmittel nach Wahl', 'adoçante a gosto'),
  ('Tajin chili-lime seasoning', 'tajin-chili-lime-seasoning', 'seasoning', '{"Tajin chili-lime seasoning (or cayenne)"}',
    'assaisonnement Tajin piment-citron vert', 'condimento Tajín chile-lima',
    'Tajin Chili-Limetten-Gewürz', 'tempero Tajín pimenta-lima'),
  ('Thin Mint cookies, crushed', 'thin-mint-cookies-crushed', 'other', '{}',
    'biscuits Thin Mint écrasés', 'galletas Thin Mint trituradas',
    'zerdrückte Thin-Mint-Kekse', 'biscoitos Thin Mint esmagados'),
  ('toasted rolled oats', 'toasted-rolled-oats', 'grain', '{}',
    'flocons d''avoine grillés', 'avena en copos tostada', 'geröstete Haferflocken', 'aveia em flocos torrada'),
  ('toasted sesame seeds', 'toasted-sesame-seeds', 'seed', '{}',
    'graines de sésame grillées', 'semillas de sésamo tostadas',
    'geröstete Sesamsamen', 'sementes de gergelim torradas'),
  ('toasted whole almonds, chopped', 'toasted-whole-almonds-chopped', 'nut', '{}',
    'amandes entières grillées hachées', 'almendras enteras tostadas picadas',
    'gehackte geröstete ganze Mandeln', 'amêndoas inteiras torradas picadas'),
  ('ube paste (purple yam)', 'ube-paste', 'vegetable', '{}',
    'pâte d''ube (igname violet)', 'pasta de ube (ñame morado)',
    'Ube-Paste (violetter Yams)', 'pasta de ube (inhame roxo)'),
  ('vanilla sandwich cookies, chopped', 'vanilla-sandwich-cookies-chopped', 'other', '{}',
    'biscuits sandwich à la vanille hachés', 'galletas sándwich de vainilla picadas',
    'gehackte Vanille-Sandwich-Kekse', 'biscoitos recheados de baunilha picados'),
  ('vanilla shortbread cookies, crumbled', 'vanilla-shortbread-cookies-crumbled', 'other', '{}',
    'sablés à la vanille émiettés', 'galletas de mantequilla de vainilla desmenuzadas',
    'zerbröselte Vanille-Mürbeteigkekse', 'biscoitos amanteigados de baunilha esfarelados'),
  ('vegan cookie dough bites', 'vegan-cookie-dough-bites', 'other', '{}',
    'bouchées de pâte à cookies végane', 'bocaditos de masa de galleta vegana',
    'vegane Keksteigstücke', 'pedacinhos de massa de biscoito vegana'),
  ('vegan Oreo cookies, crushed', 'vegan-oreo-cookies-crushed', 'other', '{}',
    'biscuits Oreo végans écrasés', 'galletas Oreo veganas trituradas',
    'zerdrückte vegane Oreo-Kekse', 'biscoitos Oreo veganos esmagados'),
  ('watermelon puree', 'watermelon-puree', 'fruit', '{"watermelon puree (seedless, blended)"}',
    'purée de pastèque', 'puré de sandía', 'Wassermelonenpüree', 'purê de melancia'),
  ('whiskey (bourbon or Irish)', 'whiskey-bourbon-or-irish', 'other', '{}',
    'whiskey (bourbon ou irlandais)', 'whisky (bourbon o irlandés)',
    'Whiskey (Bourbon oder Irish)', 'uísque (bourbon ou irlandês)'),
  ('white miso paste', 'white-miso-paste', 'condiment', '{}',
    'pâte de miso blanc', 'pasta de miso blanco',
    'weiße Miso-Paste', 'pasta de missô branco'),
  ('wildflower honey', 'wildflower-honey', 'sweetener', '{}',
    'miel de fleurs sauvages', 'miel de flores silvestres',
    'Wildblütenhonig', 'mel de flores silvestres');

-- Link the canonical names:
UPDATE ingredients i SET master_ingredient_id = m.id
FROM master_ingredients m
WHERE i.name = m.name AND i.master_ingredient_id IS NULL
  AND m.slug IN ('malted-milk-powder','maraschino-cherries-chopped','medjool-dates-pitted-chopped',
    'mini-chocolate-almond-butter-cups-chopped','mint-oreo-cookies-crushed','mixed-berry-compote',
    'mixed-berry-jam-new','natural-peanut-butter','oat-streusel-crumbles','oat-cobbler-crumbles',
    'oat-almond-streusel-crumbles','pancake-crumbles','pie-crust-crumbles','pineapple-puree',
    'pink-peppercorns-lightly-crushed','powdered-sugar-dusting','raisin-bread-crumbles-toasted',
    'raisins-plain','raspberry-sauce','ripe-avocado-mashed','roasted-macadamia-nuts-chopped',
    'roasted-salted-cashews-chopped','saffron-threads','salted-roasted-peanuts-chopped',
    'semi-sweet-chocolate-chips','shortbread-cookie-crumbles','shredded-coconut-toasted',
    'smoked-sea-salt','snickerdoodle-cookies-crumbled','snickers-bars-chopped',
    'soft-goat-cheese-chevre','soft-nougat-candy-chopped','stewed-rhubarb-compote',
    'sugar-free-hot-fudge-sauce','sugar-free-oreo-cookies-crushed','sugar-free-sprinkles',
    'sweetened-shredded-coconut','sweetener-of-choice','tajin-chili-lime-seasoning',
    'thin-mint-cookies-crushed','toasted-rolled-oats','toasted-sesame-seeds',
    'toasted-whole-almonds-chopped','ube-paste','vanilla-sandwich-cookies-chopped',
    'vanilla-shortbread-cookies-crumbled','vegan-cookie-dough-bites','vegan-oreo-cookies-crushed',
    'watermelon-puree','whiskey-bourbon-or-irish','white-miso-paste','wildflower-honey');

-- Link "malted milk powder (Ovaltine or Horlicks)" to existing 'malted milk powder' master
UPDATE ingredients SET master_ingredient_id = (SELECT id FROM master_ingredients WHERE slug = 'malted-milk-powder')
WHERE name = 'malted milk powder (Ovaltine or Horlicks)' AND master_ingredient_id IS NULL;

-- Link alias variants:
UPDATE ingredients SET master_ingredient_id = (SELECT id FROM master_ingredients WHERE slug = 'oat-cobbler-crumbles')
WHERE name = 'oat cobbler crumbles (baked + cooled)' AND master_ingredient_id IS NULL;
UPDATE ingredients SET master_ingredient_id = (SELECT id FROM master_ingredients WHERE slug = 'tajin-chili-lime-seasoning')
WHERE name = 'Tajin chili-lime seasoning (or cayenne)' AND master_ingredient_id IS NULL;
UPDATE ingredients SET master_ingredient_id = (SELECT id FROM master_ingredients WHERE slug = 'watermelon-puree')
WHERE name = 'watermelon puree (seedless, blended)' AND master_ingredient_id IS NULL;

-- Remaining LINK-only (existing master rows):
UPDATE ingredients SET master_ingredient_id = '76bc33db-bb22-4639-bda6-724306cb13b5'
WHERE name = 'ripe banana, mashed' AND master_ingredient_id IS NULL;
UPDATE ingredients SET master_ingredient_id = (SELECT id FROM master_ingredients WHERE slug = 'oreo-cookies')
WHERE name = 'Oreo cookies, finely crushed' AND master_ingredient_id IS NULL;
UPDATE ingredients SET master_ingredient_id = (SELECT id FROM master_ingredients WHERE slug = 'sweet-cherries-pureed')
WHERE name = 'sweet cherries, pureed' AND master_ingredient_id IS NULL;
UPDATE ingredients SET master_ingredient_id = (SELECT id FROM master_ingredients WHERE slug = 'frozen-peaches')
WHERE name = 'frozen peaches' AND master_ingredient_id IS NULL;
UPDATE ingredients SET master_ingredient_id = (SELECT id FROM master_ingredients WHERE name = 'prosecco')
WHERE name = 'prosecco (or dry sparkling wine)' AND master_ingredient_id IS NULL;
