-- Phase 2b batch 4: final 17 existing master_ingredients rows (r–z)

UPDATE master_ingredients SET name_fr = 'poire mûre',                 name_es = 'pera madura',                      name_de = 'reife Birne',                       name_pt = 'pera madura'                             WHERE name = 'ripe pear';
UPDATE master_ingredients SET name_fr = 'poires mûres',               name_es = 'peras maduras',                    name_de = 'reife Birnen',                      name_pt = 'peras maduras'                           WHERE name = 'ripe pears';
UPDATE master_ingredients SET name_fr = 'flocons d''avoine',          name_es = 'avena en copos',                   name_de = 'Haferflocken',                      name_pt = 'aveia em flocos'                         WHERE name = 'rolled oats';
UPDATE master_ingredients SET name_fr = 'jus de pamplemousse rose',   name_es = 'jugo de pomelo rosa',              name_de = 'rosa Grapefruitsaft',               name_pt = 'suco de toranja rosa'                    WHERE name = 'ruby grapefruit juice';
UPDATE master_ingredients SET name_fr = 'carambole',                  name_es = 'carambola',                        name_de = 'Sternfrucht',                       name_pt = 'carambola'                               WHERE name = 'starfruit';
UPDATE master_ingredients SET name_fr = 'fraises',                    name_es = 'fresas',                           name_de = 'Erdbeeren',                         name_pt = 'morangos'                                WHERE name = 'strawberries';
UPDATE master_ingredients SET name_fr = 'protéine en poudre fraise',  name_es = 'proteína en polvo de fresa',       name_de = 'Erdbeer-Proteinpulver',             name_pt = 'proteína em pó de morango'               WHERE name = 'strawberry protein powder';
UPDATE master_ingredients SET name_fr = 'purée de fraises',           name_es = 'puré de fresa',                    name_de = 'Erdbeerpüree',                      name_pt = 'purê de morango'                         WHERE name = 'strawberry puree';
UPDATE master_ingredients SET name_fr = 'purée fraise-banane',        name_es = 'puré de fresa y plátano',          name_de = 'Erdbeer-Bananen-Püree',             name_pt = 'purê de morango e banana'                WHERE name = 'strawberry-banana puree';
UPDATE master_ingredients SET name_fr = 'mélange fraise-pastèque',    name_es = 'mezcla de fresa y sandía',         name_de = 'Erdbeer-Wassermelonen-Mischung',    name_pt = 'mistura de morango e melancia'           WHERE name = 'strawberry-watermelon blend';
UPDATE master_ingredients SET name_fr = 'cerises douces',             name_es = 'cerezas dulces',                   name_de = 'süße Kirschen',                     name_pt = 'cerejas doces'                           WHERE name = 'sweet cherries';
UPDATE master_ingredients SET name_fr = 'jus de mandarine',           name_es = 'jugo de mandarina',                name_de = 'Mandarinensaft',                    name_pt = 'suco de tangerina'                       WHERE name = 'tangerine juice';
UPDATE master_ingredients SET name_fr = 'mélange de fruits tropicaux', name_es = 'mezcla de frutas tropicales',     name_de = 'Tropenfruchtmischung',              name_pt = 'mistura de frutas tropicais'             WHERE name = 'tropical fruit blend';
UPDATE master_ingredients SET name_fr = 'mélange de jus de fruits tropicaux', name_es = 'mezcla de jugos tropicales', name_de = 'Tropenfruchtsaft-Mischung',       name_pt = 'mistura de sucos tropicais'              WHERE name = 'tropical fruit juice blend';
UPDATE master_ingredients SET name_fr = 'pastèque',                   name_es = 'sandía',                           name_de = 'Wassermelone',                      name_pt = 'melancia'                                WHERE name = 'watermelon';
UPDATE master_ingredients SET name_fr = 'mélange pastèque-fruits rouges', name_es = 'mezcla de sandía y frutos rojos', name_de = 'Wassermelonen-Beeren-Mischung',   name_pt = 'mistura de melancia e frutas vermelhas'  WHERE name = 'watermelon-berry blend';
UPDATE master_ingredients SET name_fr = 'yaourt (toute saveur)',      name_es = 'yogur (cualquier sabor)',          name_de = 'Joghurt (beliebige Sorte)',         name_pt = 'iogurte (qualquer sabor)'                WHERE name = 'yogurt (any flavor)';
